on: [push, pull_request]
name: release
jobs:
  build:

    strategy:
      matrix:
        name: [main-windows-amd64,main-linux-amd64]
        include:
          - name: main-windows-amd64
            os: windows
            arch: amd64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1'
    - run: go version
      
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build project
      run: go build -o ${{ matrix.name }}
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}

    - name: Upload releases
      if: startsWith(github.ref, 'refs/tags/') # on tag
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: main-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true